<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CShells.AspNetCore.Abstractions" />
    <ProjectReference Include="../../../src/Orbyss.Localization/Orbyss.Localization.csproj" />
    <ProjectReference Include="../../../src/Orbyss.Localization.Formats/Orbyss.Localization.Formats.csproj" />
    <ProjectReference Include="../../../src/Orbyss.Localization.Web.Management/Orbyss.Localization.Web.Management.csproj" />
    <ProjectReference Include="../../../src/Orbyss.Localization.Web.Runtime/Orbyss.Localization.Web.Runtime.csproj" />
  </ItemGroup>
</Project>
